import Link from 'next/link';
import ProductCard from '@/components/ProductCard';
import {categories,products,featuredSellers} from '@/lib/data';

export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><div className="eyebrow">South Sudan’s local marketplace</div><h1>Buy. Sell.<br/>Discover.</h1><p>Your marketplace for products, services and opportunities across South Sudan — built to make local commerce simple, trusted and accessible.</p><form className="searchbox" action="/marketplace"><input name="q" placeholder="What are you looking for?"/><button>Search marketplace</button></form><div className="actions"><Link className="primary" href="/marketplace">Browse Marketplace</Link><Link className="secondary" href="/sell">Start Selling</Link></div></div><div className="hero-card"><h2>Marketplace near you</h2><div className="stat"><span>Popular location</span><b>Juba</b></div><div className="stat"><span>Categories</span><b>{categories.length}+</b></div><div className="stat"><span>Ways to trade</span><b>Contact · Order</b></div><div className="stat"><span>Built for</span><b>Mobile first</b></div></div></div></section>
<section id="categories"><div className="container"><div className="section-head"><div><h2>Explore categories</h2><p>Find what you need quickly.</p></div><Link href="/marketplace">View marketplace →</Link></div><div className="category-grid">{categories.slice(0,14).map((c,i)=><Link key={c} className="category" href={`/marketplace?category=${encodeURIComponent(c)}`}>{['📱','💻','🚗','🏠','👕','🛋️','💼','🛠️','🌾','✨','⚽','🧸','🏢','➕'][i]}<br/>{c}</Link>)}</div></div></section>
<section><div className="container"><div className="section-head"><div><h2>Trending near you</h2><p>Fresh listings from local sellers.</p></div><Link href="/marketplace">See all →</Link></div><div className="product-grid">{products.slice(0,8).map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
<section><div className="container"><div className="section-head"><div><h2>Featured sellers</h2><p>Discover growing local businesses.</p></div></div><div className="benefits">{featuredSellers.slice(0,3).map(s=><div className="benefit" key={s.name}><span className="chip">Seller</span><h3>{s.name}</h3><p>{s.category} · {s.location}</p></div>)}</div></div></section>
<section><div className="container"><div className="section-head"><div><h2>Why Dukanen?</h2><p>A marketplace designed around real local buying and selling.</p></div></div><div className="benefits"><div className="benefit"><h3>Discover</h3><p>Find products and services around you with clear categories and location-first browsing.</p></div><div className="benefit"><h3>Sell</h3><p>Turn your products, skills and business inventory into opportunities with simple listing tools.</p></div><div className="benefit"><h3>Connect</h3><p>Connect directly with local sellers and businesses while keeping trust and safety visible.</p></div></div></div></section>
</>}
