const FALLBACK_SUPABASE_URL = 'https://rkjrywlddrgxlxghtjoz.supabase.co'
const FALLBACK_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJranJ5d2xkZHJneGx4Z2h0am96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczNzk5NjksImV4cCI6MjEwMjk1NTk2OX0.76183VoES_-aTXLODssZINExDKhEGPfoF0bjt2OH3Ak'

export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || FALLBACK_SUPABASE_URL
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || FALLBACK_SUPABASE_ANON_KEY

export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_ANON_KEY)
