export const SUPABASE_URL = 'https://rkjrywlddrgxlxghtjoz.supabase.co'
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJranJ5d2xkZHJneGx4Z2h0am96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODczNzk5NjksImV4cCI6MjEwMjk1NTk2OX0.76183VoES_-aTXLODssZINExDKhEGPfoF0bjt2OH3Ak'

export const hasSupabaseConfig = true
